[versions]
kotlin = "1.9.22"
ktlint = "10.2.0"
detekt = "1.18.1"
owasp = "6.4.1.1"
junit-jupiter-engine = "5.10.1"
assertj = "3.21.0"
kotest = "5.0.0"
ktilint-pinterest = "0.42.1"

[libraries]
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter-engine" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter-engine" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
kotest-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
detekt-cli = { module = "io.gitlab.arturbosch.detekt:detekt-cli", version.ref = "detekt" }
sportbugs = {module = "com.github.spotbugs.snom:spotbugs-gradle-plugin", version = "5.2.1"}

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
owasp = { id = "org.owasp.dependencycheck", version.ref = "owasp" }
