[versions]
kotlin = "2.3.20"
ktlint = "14.0.1"
detekt = "1.23.6"
owasp = "12.2.0"
junit = "6.0.3"
assertj = "3.27.6"
kotest = "6.1.11"
ktlintPinterest = "1.8.0"
java = "21"

[libraries]
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
kotest-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
detekt-cli = { module = "io.gitlab.arturbosch.detekt:detekt-cli", version.ref = "detekt" }

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
owasp = { id = "org.owasp.dependencycheck", version.ref = "owasp" }
